=== shlomif/perl-xml-grammar-productssyndication/perl/XML-Grammar-ProductsSyndication/extradata/product-syndication.dtd
<!-- ....................................................................... -->
<!-- MYML DTD  ............................................................. -->
<!-- file: myml-1_0.dtd -->

<!-- This is the DTD driver for myml 1.0.

     Please use this formal public identifier to identify it:

         "-//MY COMPANY//DTD XHTML MYML 1.0//EN"

     And this namespace for myml-unique elements:

         xmlns:myml="http://www.example.com/xmlns/myml"
-->
<!ENTITY % XHTML.version  "-//MY COMPANY//DTD XHTML MYML 1.0//EN" >

<!-- reserved for use with document profiles -->
<!ENTITY % XHTML.profile  "" >

<!-- Tell the framework to use our qualified names module as an extra qname
driver -->
<!ENTITY % xhtml-qname-extra.mod
     SYSTEM "myml-qname-1.mod" >

<!-- Define the Content Model for the framework to use -->
<!ENTITY % xhtml-model.mod
	 SYSTEM "myml-model-1.mod" >

<!-- Disable bidirectional text support -->
<!ENTITY % XHTML.bidi  "IGNORE" >

<!ENTITY % xhtml-legacy-redecl.mod
     SYSTEM "xhtml-legacy-redecl-1.mod" >
%xhtml-legacy-redecl.mod;

<!-- Basic Text Module (Required)  ............................... -->
<!ENTITY % xhtml-text.mod
     SYSTEM "xhtml-text-1.mod" >
%xhtml-text.mod;

<!-- Hypertext Module (required) ................................. -->
<!ENTITY % xhtml-hypertext.mod
     SYSTEM "xhtml-hypertext-1.mod" >
%xhtml-hypertext.mod;

<!-- Lists Module (required)  .................................... -->
<!ENTITY % xhtml-list.mod
     SYSTEM "xhtml-list-1.mod" >
%xhtml-list.mod;

<!ENTITY % xhtml-pres.mod
     SYSTEM "xhtml-pres-1.mod" >
%xhtml-pres.mod;

<!-- My Elements Module   ........................................ 
<!ENTITY % MyML-elements.mod
     SYSTEM "myml-elements-1.mod" >
%MyML-elements.mod;
-->

<!-- XHTML Images module  ........................................ -->
<!ENTITY % xhtml-image.mod
   SYSTEM "xhtml-image-1.mod" >
%xhtml-image.mod;


<!ELEMENT product-syndication (meta?,data)>
<!ELEMENT meta (#PCDATA)>
<!ELEMENT data (cat)>
<!ELEMENT cat (title,desc?,(cat|prod|set)*)>
<!ELEMENT prod (title,isbn,creator*,ref*,desc?)>
<!ELEMENT set (title,prod*,desc?)>
<!ELEMENT desc ((%Flow.mix;)*)>
<!ELEMENT isbn (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT creator (#PCDATA)>
<!ELEMENT ref EMPTY>
<!ATTLIST cat id ID #REQUIRED>
<!ATTLIST prod id ID #REQUIRED>
<!ATTLIST creator type (author|artist|performer|composer|director) "author">
<!ATTLIST ref href CDATA "" affil CDATA "">
<!ATTLIST set id ID #REQUIRED>
<!ATTLIST isbn disable (0|1) "0">
<!ATTLIST desc appendtoc CDATA "">

=== shlomif/perl-xml-grammar-productssyndication/perl/XML-Grammar-ProductsSyndication/t/data/valid-xmls/010-disabled-isbn.xml
<?xml version='1.0' encoding='utf-8'?>
<?xml-stylesheet type="text/xml" href="product-syndication.xsl"?>
<!DOCTYPE comparison SYSTEM "product-syndication.dtd">
<product-syndication>
    <data>
        <cat id="books">
            <title>Books</title>
            <desc>
                <p>
                    These are my books.
                </p>
            </desc>
            <cat id="fiction_books">
                <title>Fiction books</title>
                <prod id="little_women">
                    <title>Little Women</title>
                    <isbn disable="1" />
                    <desc>
                        <p>
                            Little Women by Louisa May Alcott.
                        </p>
                    </desc>
                </prod>
            </cat>
            <cat id="computer_books">
                <title>Computer books</title>
            </cat>
        </cat>
    </data>
</product-syndication>

=== shlomif/perl-xml-grammar-productssyndication/xslt/valid-xmls/009-set.xml
<?xml version='1.0' encoding='utf-8'?>
<?xml-stylesheet type="text/xml" href="product-syndication.xsl"?>
<!DOCTYPE comparison SYSTEM "product-syndication.dtd">
<product-syndication>
    <data>
        <cat id="books">
            <title>Books</title>
            <desc>
                <p>
                    These are my books.
                </p>
            </desc>
            <cat id="fiction_books">
                <title>Fiction books</title>
                <prod id="little_women">
                    <title>Little Women</title>
                    <isbn>06903459409</isbn>
                    <creator type="author">Louisa May Alcott</creator>
                    <desc>
                        <p>
                            Little Women by <a href="http://en.wikipedia.org/wiki/Louisa_May_Alcott" rel="author">Louisa May Alcott</a> is an 
                            <b>early</b> and <strong>intriguing</strong>
                            book.
                        </p>
                    </desc>
                </prod>
                <prod id="around_the_world_in_80_days">
                    <title>Around the World in 80 Days</title>
                    <isbn>12340987</isbn>
                    <ref 
                        href="http://www.amazon.com/exec/obidos/ASIN/1577656806/ref=nosim/shlomifishhom-20" 
                        affil="amazon" 
                        />
                    <ref
                        href="http://search.barnesandnoble.com/booksearch/isbnInquiry.asp?z=y&amp;EAN=9780140367119&amp;itm=1"
                        affil="bn"
                        />
                    <desc>
                        <p>
                            Around the world by Jules Verne. About Fog and
                            Passpartu.
                        </p>
                    </desc>
                </prod>
            </cat>
            <prod id="not_a_book">
                <title>This is a book that's not a book</title>
                <isbn>06454545</isbn>
                <desc>
                    <p>
                        I came. I saw. I conquered.
                    </p>
                </desc>
            </prod>
            <cat id="movies">
                <title>Movies</title>
                <set id="indiana_jones">
                    <title>The Indiana Jones Trilogy</title>
                    <prod id="indiana_jones_1">
                        <title>Raiders of the Lost Ark</title>
                        <isbn>111</isbn>
                    </prod>
                    <prod id="indiana_jones_2">
                        <title>Indiana Jones 2: The Temple of Doom</title>
                        <isbn>112</isbn>
                    </prod>
                    <prod id="indiana_jones_3">
                        <title>Indiana Jones and the Last Crusade</title>
                        <isbn>113</isbn>
                    </prod>
                    <desc>
                        <p>
                            Three great movies, high adventure, etc.
                        </p>
                    </desc>
                </set>
            </cat>
        </cat>
    </data>
</product-syndication>

=== shlomif/perl-xml-grammar-productssyndication/perl/XML-Grammar-ProductsSyndication/t/data/valid-xmls/images-test.xml
<?xml version='1.0' encoding='utf-8'?>
<?xml-stylesheet type="text/xml" href="product-syndication.xsl"?>
<!DOCTYPE comparison SYSTEM "product-syndication.dtd">
<product-syndication>
    <data>
        <cat id="books">
            <title>Books</title>
            <desc>
                <p>
                    These are my books.
                </p>
            </desc>
            <cat id="fiction_books">
                <title>Fiction books</title>
                <prod id="little_women">
                    <title>Little Women</title>
                    <isbn>0451529308</isbn>
                    <desc>
                        <p>
                            Little Women by Louisa May Alcott.
                        </p>
                    </desc>
                </prod>
                <prod id="around_the_world_in_80_days">
                    <title>Around the World in 80 Days</title>
                    <isbn>014036711X</isbn>
                    <desc>
                        <p>
                            Around the world by Jules Verne. About Fog and
                            Passpartu.
                        </p>
                    </desc>
                </prod>
            </cat>
            <cat id="computer_books">
                <title>Computer books</title>
                <prod id="programming_perl">
                    <title>Programming Perl, 3rd Edition</title>
                    <isbn>0596000278</isbn>
                    <desc>
                        <p>
                            The Camel Book.
                        </p>
                    </desc>
                </prod>
            </cat>
        </cat>
    </data>
</product-syndication>

=== shlomif/perl-xml-grammar-productssyndication/perl/XML-Grammar-ProductsSyndication/t/data/valid-xmls/004-products-with-creators.xml
<?xml version='1.0' encoding='utf-8'?>
<?xml-stylesheet type="text/xml" href="product-syndication.xsl"?>
<!DOCTYPE comparison SYSTEM "product-syndication.dtd">
<product-syndication>
    <data>
        <cat id="books">
            <title>Books</title>
            <desc>
                <p>
                    These are my books.
                </p>
            </desc>
            <cat id="fiction_books">
                <title>Fiction books</title>
                <prod id="little_women">
                    <title>Little Women</title>
                    <isbn>06903459409</isbn>
                    <creator type="author">Louisa May Alcott</creator>
                    <desc>
                        <p>
                            Little Women by Louisa May Alcott.
                        </p>
                    </desc>
                </prod>
                <prod id="around_the_world_in_80_days">
                    <title>Around the World in 80 Days</title>
                    <isbn>12340987</isbn>
                    <desc>
                        <p>
                            Around the world by Jules Verne. About Fog and
                            Passpartu.
                        </p>
                    </desc>
                </prod>
            </cat>
            <prod id="not_a_book">
                <title>This is a book that's not a book</title>
                <isbn>06454545</isbn>
                <desc>
                    <p>
                        I came. I saw. I conquered.
                    </p>
                </desc>
            </prod>
            <cat id="non_books">
                <title>Non books</title>
                <prod id="beatles_blue_album">
                    <title>The Beatles - The Blue Album</title>
                    <isbn>56565656</isbn>
                    <creator type="artist">The Beatles</creator>
                    <desc>
                        <p>
                            I became addicted to "Come Togethere".
                        </p>
                    </desc>
                </prod>
            </cat>
        </cat>
    </data>
</product-syndication>

=== shlomif/perl-xml-grammar-productssyndication/perl/XML-Grammar-ProductsSyndication/t/data/valid-xmls/0031-with-products.xml
<?xml version='1.0' encoding='utf-8'?>
<?xml-stylesheet type="text/xml" href="product-syndication.xsl"?>
<!DOCTYPE comparison SYSTEM "product-syndication.dtd">
<product-syndication>
    <data>
        <cat id="books">
            <title>Books</title>
            <desc>
                <p>
                    These are my books.
                </p>
            </desc>
            <cat id="fiction_books">
                <title>Fiction books</title>
                <prod id="little_women">
                    <title>Little Women</title>
                    <isbn>06903459409</isbn>
                    <desc>
                        <p>
                            Little Women by Louisa May Alcott.
                        </p>
                    </desc>
                </prod>
                <prod id="around_the_world_in_80_days">
                    <title>Around the World in 80 Days</title>
                    <isbn>12340987</isbn>
                    <desc>
                        <p>
                            Around the world by Jules Verne. About Fog and
                            Passpartu.
                        </p>
                    </desc>
                </prod>
            </cat>
            <prod id="not_a_book">
                <title>This is a book that's not a book</title>
                <isbn>06454545</isbn>
                <desc>
                    <p>
                        I came. I saw. I conquered.
                    </p>
                </desc>
            </prod>
            <cat id="computer_books">
                <title>Computer books</title>
            </cat>
        </cat>
    </data>
</product-syndication>
